export enum AccessScopes {
  USER_CREATE = 'user:create',
  USER_DELETE = 'user:delete',
  USER_UPDATE = 'user:update',
  USER_VIEW = 'user:view',
  USER_VIEW_ALL = 'user:view-all',
  USER_ADD_BRANCH = 'user:add-branch',
  ROLE_VIEW = 'role:view',
  BRANCH_CREATE = 'branch:create',
  BRANCH_VIEW = 'branch:view',
  BRANCH_VIEW_ALL = 'branch:view-all',
  REGIONAL_CREATE = 'regional:create',
  REGIONAL_VIEW = 'regional:view',
  REGIONAL_VIEW_ALL = 'regional:view-all',
  CLIENT_CREATE = 'client:create',
  CLIENT_DELETE = 'client:delete',
  CLIENT_UPDATE = 'client:update',
  CLIENT_VIEW = 'client:view',
  CLIENT_VIEW_ALL = 'client:view-all',
  DOCUMENT_CREATE = 'document:create',
  DOCUMENT_UPDATE = 'document:update',
  DOCUMENT_VIEW = 'document:view',
  DOCUMENT_VIEW_ALL = 'document:view-all',
  CITY_VIEW = 'city:view',
}
